// Demonstration data, not live property advertisements. Prices are in USD.
export const listings = [
  {
    "id": 1,
    "type": "House",
    "name": "Lawndale Residence 1",
    "description": "This sample house in Lawndale offers 6 bedrooms, 3 bathrooms, and 4200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House1",
    "imageLg": "House1Lg",
    "country": "United States",
    "address": "7240C Argyle St. Lawndale, CA 90260",
    "bedrooms": "6",
    "bathrooms": "3",
    "surface": "4200 sq ft",
    "year": "2016",
    "price": 110000,
    "agent": {
      "image": "Agent1",
      "name": "Patricia Tullert",
      "slug": "patricia-tullert"
    },
    "city": "Lawndale",
    "purpose": "sale"
  },
  {
    "id": 2,
    "type": "House",
    "name": "Ottawa Residence 2",
    "description": "This sample house in Ottawa offers 6 bedrooms, 3 bathrooms, and 4200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House2",
    "imageLg": "House2Lg",
    "country": "Canada",
    "address": "124 Cedar Avenue, Ottawa, ON K1S 2N1",
    "bedrooms": "6",
    "bathrooms": "3",
    "surface": "4200 sq ft",
    "year": "2016",
    "price": 140000,
    "agent": {
      "image": "Agent2",
      "name": "Daryl Hawker",
      "slug": "daryl-hawker"
    },
    "city": "Ottawa",
    "purpose": "sale"
  },
  {
    "id": 3,
    "type": "House",
    "name": "Alexandria Residence 3",
    "description": "This sample house in Alexandria offers 6 bedrooms, 3 bathrooms, and 4200 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House3",
    "imageLg": "House3Lg",
    "country": "United States",
    "address": "2 Glen Creek St. Alexandria, VA 22304",
    "bedrooms": "6",
    "bathrooms": "3",
    "surface": "4200 sq ft",
    "year": "2016",
    "price": 1860,
    "agent": {
      "image": "Agent3",
      "name": "Amado Smith",
      "slug": "amado-smith"
    },
    "city": "Alexandria",
    "purpose": "rent"
  },
  {
    "id": 4,
    "type": "House",
    "name": "Calgary Residence 4",
    "description": "This sample house in Calgary offers 6 bedrooms, 3 bathrooms, and 4200 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House4",
    "imageLg": "House4Lg",
    "country": "Canada",
    "address": "148 Park Avenue, Calgary, AB T2P 1J9",
    "bedrooms": "6",
    "bathrooms": "3",
    "surface": "4200 sq ft",
    "year": "2016",
    "price": 1990,
    "agent": {
      "image": "Agent4",
      "name": "Kaitlyn Gonzalez",
      "slug": "kaitlyn-gonzalez"
    },
    "city": "Calgary",
    "purpose": "rent"
  },
  {
    "id": 5,
    "type": "House",
    "name": "Warminster Residence 5",
    "description": "This sample house in Warminster offers 5 bedrooms, 3 bathrooms, and 4200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House5",
    "imageLg": "House5Lg",
    "country": "United States",
    "address": "28 Westport Dr. Warminster, PA 18974",
    "bedrooms": "5",
    "bathrooms": "3",
    "surface": "4200 sq ft",
    "year": "2015",
    "price": 210000,
    "agent": {
      "image": "Agent5",
      "name": "Grover Robinson",
      "slug": "grover-robinson"
    },
    "city": "Warminster",
    "purpose": "sale"
  },
  {
    "id": 6,
    "type": "House",
    "name": "Toronto Residence 6",
    "description": "This sample house in Toronto offers 6 bedrooms, 3 bathrooms, and 6200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House6",
    "imageLg": "House6Lg",
    "country": "Canada",
    "address": "172 Maple Avenue, Toronto, ON M4B 1B3",
    "bedrooms": "6",
    "bathrooms": "3",
    "surface": "6200 sq ft",
    "year": "2014",
    "price": 220000,
    "agent": {
      "image": "Agent6",
      "name": "Karen Sorensen",
      "slug": "karen-sorensen"
    },
    "city": "Toronto",
    "purpose": "sale"
  },
  {
    "id": 7,
    "type": "Apartment",
    "name": "Ottawa Apartment 7",
    "description": "This sample apartment in Ottawa offers 2 bedrooms, 1 bathrooms, and 1200 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "Apartment1",
    "imageLg": "Apartment1Lg",
    "country": "Canada",
    "address": "184 Cedar Avenue, Ottawa, ON K1S 2N1",
    "bedrooms": "2",
    "bathrooms": "1",
    "surface": "1200 sq ft",
    "year": "2012",
    "price": 1240,
    "agent": {
      "image": "Agent7",
      "name": "Jawhar Shamil Naser",
      "slug": "jawhar-shamil-naser"
    },
    "city": "Ottawa",
    "purpose": "rent"
  },
  {
    "id": 8,
    "type": "Apartment",
    "name": "Warminster Apartment 8",
    "description": "This sample apartment in Warminster offers 3 bedrooms, 1 bathrooms, and 1000 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "Apartment2",
    "imageLg": "Apartment2Lg",
    "country": "United States",
    "address": "28 Westport Dr. Warminster, PA 18974",
    "bedrooms": "3",
    "bathrooms": "1",
    "surface": "1000 sq ft",
    "year": "2011",
    "price": 1305,
    "agent": {
      "image": "Agent8",
      "name": "Juana Douglass",
      "slug": "juana-douglass"
    },
    "city": "Warminster",
    "purpose": "rent"
  },
  {
    "id": 9,
    "type": "Apartment",
    "name": "Cocoa Apartment 9",
    "description": "This sample apartment in Cocoa offers 2 bedrooms, 1 bathrooms, and 1100 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "Apartment3",
    "imageLg": "Apartment3Lg",
    "country": "United States",
    "address": "84 Woodland St. Cocoa, FL 32927",
    "bedrooms": "2",
    "bathrooms": "1",
    "surface": "1100 sq ft",
    "year": "2011",
    "price": 40000,
    "agent": {
      "image": "Agent9",
      "name": "Jerry Schenck",
      "slug": "jerry-schenck"
    },
    "city": "Cocoa",
    "purpose": "sale"
  },
  {
    "id": 10,
    "type": "House",
    "name": "Halifax Residence 10",
    "description": "This sample house in Halifax offers 5 bedrooms, 3 bathrooms, and 3200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House7",
    "imageLg": "House7Lg",
    "country": "Canada",
    "address": "220 Aspen Avenue, Halifax, NS B3H 1Y2",
    "bedrooms": "5",
    "bathrooms": "3",
    "surface": "3200 sq ft",
    "year": "2015",
    "price": 117000,
    "agent": {
      "image": "Agent10",
      "name": "Vera Levesque",
      "slug": "vera-levesque"
    },
    "city": "Halifax",
    "purpose": "sale"
  },
  {
    "id": 11,
    "type": "House",
    "name": "Toronto Residence 11",
    "description": "This sample house in Toronto offers 7 bedrooms, 2 bathrooms, and 2200 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House8",
    "imageLg": "House8Lg",
    "country": "Canada",
    "address": "232 Maple Avenue, Toronto, ON M4B 1B3",
    "bedrooms": "7",
    "bathrooms": "2",
    "surface": "2200 sq ft",
    "year": "2019",
    "price": 2900,
    "agent": {
      "image": "Agent11",
      "name": "Sofia Gomes",
      "slug": "sofia-gomes"
    },
    "city": "Toronto",
    "purpose": "rent"
  },
  {
    "id": 12,
    "type": "House",
    "name": "Alexandria Residence 12",
    "description": "This sample house in Alexandria offers 4 bedrooms, 4 bathrooms, and 4600 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House9",
    "imageLg": "House9Lg",
    "country": "United States",
    "address": "2 Glen Creek St. Alexandria, VA 22304",
    "bedrooms": "4",
    "bathrooms": "4",
    "surface": "4600 sq ft",
    "year": "2015",
    "price": 3030,
    "agent": {
      "image": "Agent12",
      "name": "Raymond Hood",
      "slug": "raymond-hood"
    },
    "city": "Alexandria",
    "purpose": "rent"
  },
  {
    "id": 13,
    "type": "House",
    "name": "Vancouver Residence 13",
    "description": "This sample house in Vancouver offers 5 bedrooms, 2 bathrooms, and 5200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House10",
    "imageLg": "House10Lg",
    "country": "Canada",
    "address": "256 Willow Avenue, Vancouver, BC V5K 0A1",
    "bedrooms": "5",
    "bathrooms": "2",
    "surface": "5200 sq ft",
    "year": "2014",
    "price": 180000,
    "agent": {
      "image": "Agent1",
      "name": "Patricia Tullert",
      "slug": "patricia-tullert"
    },
    "city": "Vancouver",
    "purpose": "sale"
  },
  {
    "id": 14,
    "type": "House",
    "name": "Warminster Residence 14",
    "description": "This sample house in Warminster offers 5 bedrooms, 2 bathrooms, and 3200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House11",
    "imageLg": "House11Lg",
    "country": "United States",
    "address": "28 Westport Dr. Warminster, PA 18974",
    "bedrooms": "5",
    "bathrooms": "2",
    "surface": "3200 sq ft",
    "year": "2011",
    "price": 213000,
    "agent": {
      "image": "Agent2",
      "name": "Daryl Hawker",
      "slug": "daryl-hawker"
    },
    "city": "Warminster",
    "purpose": "sale"
  },
  {
    "id": 15,
    "type": "House",
    "name": "Halifax Residence 15",
    "description": "This sample house in Halifax offers 4 bedrooms, 3 bathrooms, and 5200 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "House12",
    "imageLg": "House12Lg",
    "country": "Canada",
    "address": "280 Aspen Avenue, Halifax, NS B3H 1Y2",
    "bedrooms": "4",
    "bathrooms": "3",
    "surface": "5200 sq ft",
    "year": "2013",
    "price": 221000,
    "agent": {
      "image": "Agent3",
      "name": "Amado Smith",
      "slug": "amado-smith"
    },
    "city": "Halifax",
    "purpose": "sale"
  },
  {
    "id": 16,
    "type": "Apartment",
    "name": "Toronto Apartment 16",
    "description": "This sample apartment in Toronto offers 2 bedrooms, 1 bathrooms, and 1300 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "Apartment4",
    "imageLg": "Apartment4Lg",
    "country": "Canada",
    "address": "292 Maple Avenue, Toronto, ON M4B 1B3",
    "bedrooms": "2",
    "bathrooms": "1",
    "surface": "1300 sq ft",
    "year": "2011",
    "price": 1825,
    "agent": {
      "image": "Agent4",
      "name": "Kaitlyn Gonzalez",
      "slug": "kaitlyn-gonzalez"
    },
    "city": "Toronto",
    "purpose": "rent"
  },
  {
    "id": 17,
    "type": "Apartment",
    "name": "Warminster Apartment 17",
    "description": "This sample apartment in Warminster offers 3 bedrooms, 1 bathrooms, and 1000 sq ft of living space. Browse the photo and property details to compare it with other homes for sale in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "Apartment5",
    "imageLg": "Apartment5Lg",
    "country": "United States",
    "address": "28 Westport Dr. Warminster, PA 18974",
    "bedrooms": "3",
    "bathrooms": "1",
    "surface": "1000 sq ft",
    "year": "2012",
    "price": 32000,
    "agent": {
      "image": "Agent5",
      "name": "Grover Robinson",
      "slug": "grover-robinson"
    },
    "city": "Warminster",
    "purpose": "sale"
  },
  {
    "id": 18,
    "type": "Apartment",
    "name": "Vancouver Apartment 18",
    "description": "This sample apartment in Vancouver offers 3 bedrooms, 1 bathrooms, and 1200 sq ft of living space. Browse the photo and property details to compare it with other rentals in the collection. All listing details and pricing are illustrative; this property is not being advertised as available.",
    "image": "Apartment6",
    "imageLg": "Apartment6Lg",
    "country": "Canada",
    "address": "316 Willow Avenue, Vancouver, BC V5K 0A1",
    "bedrooms": "3",
    "bathrooms": "1",
    "surface": "1200 sq ft",
    "year": "2010",
    "price": 1955,
    "agent": {
      "image": "Agent6",
      "name": "Karen Sorensen",
      "slug": "karen-sorensen"
    },
    "city": "Vancouver",
    "purpose": "rent"
  }
]
